name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'index.html'  # Trigger only when index.html is changed
    branches:
      - main  # Only run on the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure correct Node.js version

      - name: Build the website
        run: echo "No build step needed for static HTML"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Deploy the root folder containing index.html
